version: '2'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    expose:
    - "3000"
    links:
    - db
    env_file:
    - ./app.env
  db:
    image: mongo
    ports:
        - "27017:27017"
    expose:
        - "27017"
